version: '3'

services:
#  selenium:
#    image: selenium/standalone-chrome
#    ports:
#      - 4444:4444
  crawler:
    build: .
    command: bash -c "python3 main.py"
    volumes:
      - .:/bookcrawler  # <--  THIS line enables hot code reloading!
    ports:
      - "8000:8000"
